CONTIKI = ../..

CONTIKIDIRS += $(CONTIKI)/libsync $(CONTIKI)/cpu/msp430/f2xxx $(CONTIKI)/libuart
PROJECT_SOURCEFILES += ntp.c sclock.c timestamp.c 

all: app app-sink

include $(CONTIKI)/Makefile.include
