CONTIKI = ../..

CONTIKIDIRS += $(CONTIKI)/libsync  $(CONTIKI)/cpu/msp430/f2xxx $(CONTIKI)/libuart
PROJECT_SOURCEFILES += ntp.c sclock.c timestamp.c uart0.c uart.c
PROJECT_SOURCEFILES += sensing.c
all: app

include $(CONTIKI)/Makefile.include
